/**
 * Maps raw extracted content to generic page documents.
 * Input: scripts/content/raw-extracted.ts (generated by extract-content)
 * Output: scripts/content/mapped-pages.cjs
 *
 * Run:
 *   npx ts-node scripts/map-extracted-to-pages.ts
 */

import path from "path";
import fs from "fs";
// Use the CJS output from extractor
// @ts-ignore
import { extractedContent } from "./content/raw-extracted.cjs";

type MappedPage = {
  route: string;
  slug: string;
  title: string;
  texts: string[];
  images: string[];
};

function routeFromFile(file: string): string {
  // Expect paths like app/.../page.tsx
  const parts = file.split(path.sep);
  const appIndex = parts.indexOf("app");
  if (appIndex === -1) return "/";
  const slice = parts.slice(appIndex + 1);
  // remove the last element (page.tsx)
  slice.pop();
  const route = "/" + slice.join("/").replace(/\/page$/, "");
  return route === "/page" ? "/" : route;
}

function slugFromRoute(route: string): string {
  if (!route || route === "/") return "home";
  return route.replace(/^\//, "").replace(/\//g, "-") || "home";
}

function titleFromRoute(route: string): string {
  if (!route || route === "/") return "Home";
  return route
    .replace(/^\//, "")
    .split("/")
    .filter(Boolean)
    .map((s) => s.replace(/-/g, " "))
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(" / ");
}

function unique<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}

const mapped: MappedPage[] = extractedContent.map((item) => {
  const route = routeFromFile(item.file);
  const slug = slugFromRoute(route);
  const title = titleFromRoute(route);
  const texts = unique(item.texts || []);
  const images = unique(item.images || []);
  return { route, slug, title, texts, images };
});

const outputPath = path.join(process.cwd(), "scripts", "content", "mapped-pages.cjs");
const content = `// Auto-generated from raw-extracted.ts by map-extracted-to-pages.ts
exports.mappedPages = ${JSON.stringify(mapped, null, 2)};
`;

fs.writeFileSync(outputPath, content, "utf8");
console.log(`✅ Wrote ${mapped.length} mapped pages to ${path.relative(process.cwd(), outputPath)}`);

